In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [23]:
data=pd.read_csv('Churn_Modelling.csv')

In [24]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [25]:
#preprocess the data
#drop irrelavant data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [26]:
#encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [27]:
#one hot encoding geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [28]:
onehot_encoder_geo.get_feature_names_out(['Geography'])
geo_encoder_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [29]:
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [30]:
#combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [31]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [ ]:
#divide the dataset into dependent and independent feature
x=data.drop(['EstimatedSalary'],axis=1)
y=data['EstimatedSalary']

In [33]:
#split the data into traing and testing data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [34]:
#scale the feature
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

In [35]:
#save the encoders and scaler
with open('label_encoder_gender.pkl','wb')as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb')as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

##ANN Regression Problem statement

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [37]:
#build our own ann model
model=Sequential([
    Dense(64,activation='relu',input_shape=(xtrain.shape[1],)),#hl1 connected with input layer
    Dense(32,activation='relu'),#hl2
    Dense(1,)#output layer for regression ->linear activation function
])

e:\AI Course\venv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
#compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [45]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
##setup the tensorboard
log_dir="logs/fit"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [47]:
##set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [48]:
#train the model
history=model.fit(
    xtrain,ytrain,
    validation_data=(xtest,ytest),
    epochs=100,
    callbacks=[early_stopping_callback,tensorflow_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100674.4062 - mae: 100674.4062 - val_loss: 98537.3125 - val_mae: 98537.3125
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99803.9844 - mae: 99803.9844 - val_loss: 97214.9375 - val_mae: 97214.9375
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98218.0547 - mae: 98218.0547 - val_loss: 93849.9453 - val_mae: 93849.9453
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 93914.1562 - mae: 93914.1562 - val_loss: 88129.4531 - val_mae: 88129.4531
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 87793.1328 - mae: 87793.1328 - val_loss: 80656.0859 - val_mae: 80656.0859
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 80509.3359 - mae: 80509.3359 - val_loss: 72350.5547 - val_mae: 72350.5547
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 70537.9844 - mae: 70537.9844 - val_loss: 64630.9844 - val_mae: 64630.9844
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63547.0273 - mae: 63547.0273 - val_loss: 58561.1836 - val_mae: 58561.1836
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 57593.5000 - mae: 57593.5000 - val_loss: 54544.9883 - val_mae: 54544.9883
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53614.8438 - mae: 53614.8438 - val_loss: 52318.4531 - val_mae: 52318.4531
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51391.6406 - mae: 51391.6406 - val_loss: 51430.7578 - val_mae: 51430.7578
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50829.7656 - mae: 50829.7656 - val_loss: 51166.4336 - val_mae: 51166.4336
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50695.8086 - mae: 50695.8086 - val_loss: 51037.6172 - val_mae: 51037.6172
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50381.5664 - mae: 50381.5664 - val_loss: 50976.6602 - val_mae: 50976.6602
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50191.9414 - mae: 50191.9414 - val_loss: 50920.0000 - val_mae: 50920.0000
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50579.5586 - mae: 50579.5586 - val_loss: 50869.6758 - val_mae: 50869.6758
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50822.5391 - mae: 50822.5391 - val_loss: 50827.6211 - val_mae: 50827.6211
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49951.2148 - mae: 49951.2148 - val_loss: 50781.2188 - val_mae: 50781.2188
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50010.1328 - mae: 50010.1328 - val_loss: 50742.7227 - val_mae: 50742.7227
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49946.1523 - mae: 49946.1523 - val_loss: 50710.5586 - val_mae: 50710.5586
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49519.7031 - mae: 49519.7031 - val_loss: 50680.3164 - val_mae: 50680.3164
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50344.2695 - mae: 50344.2695 - val_loss: 50654.8477 - val_mae: 50654.8477
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49798.5742 - mae: 49798.5742 - val_loss: 50632.0078 - val_mae: 50632.0078
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49352.8438 - mae: 49352.8438 - val_loss: 50607.8203 - val_mae: 50607.8203
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49777.5742 - mae: 49777.5742 - val_loss: 50586.5508 - val_mae: 50586.5508
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50271.4531 - mae: 50271.4531 - val_loss: 50564.2383 - val_mae: 50564.2383
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49745.6211 - mae: 49745.6211 - val_loss: 50547.6445 - val_mae: 50547.6445
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50135.6953 - mae: 50135.6953 - val_loss: 50528.1445 - val_mae: 50528.1445
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50266.9961 - mae: 50266.9961 - val_loss: 50518.8281 - val_mae: 50518.8281
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49697.9766 - mae: 49697.9766 - val_loss: 50505.3359 - val_mae: 50505.3359
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50007.6172 - mae: 50007.6172 - val_loss: 50483.8828 - val_mae: 50483.8828
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49918.5938 - mae: 49918.5938 - val_loss: 50470.7266 - val_mae: 50470.7266
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49249.6719 - mae: 49249.6719 - val_loss: 50459.3711 - val_mae: 50459.3711
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49590.8828 - mae: 49590.8828 - val_loss: 50449.3008 - val_mae: 50449.3008
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49296.5312 - mae: 49296.5312 - val_loss: 50436.4688 - val_mae: 50436.4688
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49810.0820 - mae: 49810.0820 - val_loss: 50424.2344 - val_mae: 50424.2344
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50165.2383 - mae: 50165.2383 - val_loss: 50417.4297 - val_mae: 50417.4297
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50264.3281 - mae: 50264.3281 - val_loss: 50414.6914 - val_mae: 50414.6914
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49633.8594 - mae: 49633.8594 - val_loss: 50409.0742 - val_mae: 50409.0742
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49321.8203 - mae: 49321.8203 - val_loss: 50413.7188 - val_mae: 50413.7188
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50223.4336 - mae: 50223.4336 - val_loss: 50400.5195 - val_mae: 50400.5195
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49397.2422 - mae: 49397.2422 - val_loss: 50389.4805 - val_mae: 50389.4805
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49438.3711 - mae: 49438.3711 - val_loss: 50381.6016 - val_mae: 50381.6016
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49138.1445 - mae: 49138.1445 - val_loss: 50383.0391 - val_mae: 50383.0391
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49544.7773 - mae: 49544.7773 - val_loss: 50358.6289 - val_mae: 50358.6289
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49925.5469 - mae: 49925.5469 - val_loss: 50360.3359 - val_mae: 50360.3359
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49689.8477 - mae: 49689.8477 - val_loss: 50362.8945 - val_mae: 50362.8945
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50010.3047 - mae: 50010.3047 - val_loss: 50361.1250 - val_mae: 50361.1250
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48843.8203 - mae: 48843.8203 - val_loss: 50348.7305 - val_mae: 50348.7305
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49414.8633 - mae: 49414.8633 - val_loss: 50348.7148 - val_mae: 50348.7148
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49608.9844 - mae: 49608.9844 - val_loss: 50341.7461 - val_mae: 50341.7461
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49111.6133 - mae: 49111.6133 - val_loss: 50341.5078 - val_mae: 50341.5078
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49954.5078 - mae: 49954.5078 - val_loss: 50335.0352 - val_mae: 50335.0352
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49368.0469 - mae: 49368.0469 - val_loss: 50327.7227 - val_mae: 50327.7227
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49257.8242 - mae: 49257.8242 - val_loss: 50330.0859 - val_mae: 50330.0859
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49481.5469 - mae: 49481.5469 - val_loss: 50335.0156 - val_mae: 50335.0156
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49414.4727 - mae: 49414.4727 - val_loss: 50329.0469 - val_mae: 50329.0469
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49257.4844 - mae: 49257.4844 - val_loss: 50329.9766 - val_mae: 50329.9766
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50116.4023 - mae: 50116.4023 - val_loss: 50326.3359 - val_mae: 50326.3359
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49118.8320 - mae: 49118.8320 - val_loss: 50326.2695 - val_mae: 50326.2695
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50024.9766 - mae: 50024.9766 - val_loss: 50332.2539 - val_mae: 50332.2539
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49267.6328 - mae: 49267.6328 - val_loss: 50327.2617 - val_mae: 50327.2617
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49696.7109 - mae: 49696.7109 - val_loss: 50331.1602 - val_mae: 50331.1602
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49088.2227 - mae: 49088.2227 - val_loss: 50328.7578 - val_mae: 50328.7578
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50051.8008 - mae: 50051.8008 - val_loss: 50330.7656 - val_mae: 50330.7656
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49145.5430 - mae: 49145.5430 - val_loss: 50324.8594 - val_mae: 50324.8594
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49356.0703 - mae: 49356.0703 - val_loss: 50328.8477 - val_mae: 50328.8477
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49544.7188 - mae: 49544.7188 - val_loss: 50323.4219 - val_mae: 50323.4219
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49515.7031 - mae: 49515.7031 - val_loss: 50332.3086 - val_mae: 50332.3086
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49698.6875 - mae: 49698.6875 - val_loss: 50328.8477 - val_mae: 50328.8477
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49224.1953 - mae: 49224.1953 - val_loss: 50325.8594 - val_mae: 50325.8594
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48979.8516 - mae: 48979.8516 - val_loss: 50317.8750 - val_mae: 50317.8750
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49823.3594 - mae: 49823.3594 - val_loss: 50312.0938 - val_mae: 50312.0938
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49356.5586 - mae: 49356.5586 - val_loss: 50317.9688 - val_mae: 50317.9688
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49066.3750 - mae: 49066.3750 - val_loss: 50326.0508 - val_mae: 50326.0508
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49680.2578 - mae: 49680.2578 - val_loss: 50329.6836 - val_mae: 50329.6836
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49801.6289 - mae: 49801.6289 - val_loss: 50325.5977 - val_mae: 50325.5977
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49454.4336 - mae: 49454.4336 - val_loss: 50314.3320 - val_mae: 50314.3320
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49966.8008 - mae: 49966.8008 - val_loss: 50317.2383 - val_mae: 50317.2383
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49111.8789 - mae: 49111.8789 - val_loss: 50333.5234 - val_mae: 50333.5234
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49068.6953 - mae: 49068.6953 - val_loss: 50317.5156 - val_mae: 50317.5156
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49021.7266 - mae: 49021.7266 - val_loss: 50314.8320 - val_mae: 50314.8320
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49390.4297 - mae: 49390.4297 - val_loss: 50319.1953 - val_mae: 50319.1953

In [52]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6007 (pid 26556), started 0:00:16 ago. (Use '!kill 26556' to kill it.)

In [53]:
#evaluate the model
test_loss,test_mae=model.evaluate(xtest,ytest)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51076.3164 - mae: 51076.3164
Test Loss: 50312.09375, Test MAE: 50312.09375

In [54]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.